name: build-base

on:
  # Build file modifications
  push:
    branches: [ 'master' ]
    paths: [ '.github/workflows/build-base.yml', '.devops/base-*.Dockerfile' ]
  #pull_request:
  #  branches: [ 'master' ]

  # Weekly rebuild
  schedule:
    - cron: "0 0 * * 3"

  # Manual rebuild, in case of some important upstream change
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image: [ build, opencl-intel, vulkan-radv ]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build and push Docker image (${{ matrix.image }})
        uses: macbre/push-to-ghcr@v16
        with:
          dockerfile: .devops/base-${{ matrix.image }}.Dockerfile
          context: .
          image_name: ${{ github.repository }}
          image_tag: base-${{ matrix.image }}
          github_token: ${{ secrets.GHCR_ACCESS_TOKEN }}

